//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyTweets
{
    using System;
    using System.Collections.Generic;
    
    public partial class technolgy
    {
        public int technologyid { get; set; }
        public string technologyname { get; set; }
    }
}
